spring.application.name=module2RestAPI

#H2 database configurations :-
#In datasource.url, we specified a directory for H2 so that H2 can be used as an on-disk DB & we override H2's default behaviour of using system's RAM for storage.
spring.h2.console.enabled = true
spring.datasource.url=jdbc:h2:file:/Users/harshit/Desktop/CodingShuttle/Module2RestAPI/db
spring.datasource.username=harshDB
spring.datasource.password=harshDB123

#Need the value 'create' here when we run it the first time and in successive runs,
#we set this to 'update' so that we get data persistence across multiple runs while we are using an on-disk DB.
spring.jpa.hibernate.ddl-auto=update